# Generated by Django 3.1.1 on 2020-09-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_nama'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nama',
            new_name='name',
        ),
    ]
