# Generated by Django 3.1.1 on 2020-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
