# Generated by Django 3.1.1 on 2020-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='sub_disrict',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
