# Generated by Django 3.1.1 on 2020-09-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address_sub_disrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activication_code',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
